use_frameworks!

platform :ios, '12.0'

target 'DomobAdSDK_Example' do
  pod 'DomobSDK', :path => '../'
  pod 'DomobSDK/DomobSDKAdapter', :path => '../'
  pod 'DomobSDK/GMAdSDKAdapter', :path => '../'
  pod 'DomobSDK/KSAdSDKAdapter', :path => '../'
  pod 'AnyThinkiOS','6.3.61'

end
