use_frameworks!

platform :ios, '10.0'

target 'DomobAdSDK_Example' do
  pod 'DomobAdSDK', :path => '../'

  target 'DomobAdSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
